const properties = [
  {
    id: 1,
    images: ["1.webp", "2.webp", "3.webp", "4.webp", "5.webp"],
    title: "ویلای مدرن استخردار",
    type: "ویلا",
    deal: "خرید",
    area: "۲۵۰ متر",
    rooms: "۴ خواب",
    parking: "پارکینگ",
    location: "مازندران",
    totalPrice: "۱۲,۰۰۰,۰۰۰,۰۰۰",
    meterPrice: "۴۸,۰۰۰,۰۰۰",
  },

  {
    id: 2,
    images: ["2.webp", "7.webp", "6.webp"],
    title: "آپارتمان لوکس تهران",
    type: "آپارتمان",
    deal: "خرید",
    area: "۱۸۰ متر",
    rooms: "۳ خواب",
    parking: "پارکینگ",
    location: "تهران",
    totalPrice: "۱۵,۵۰۰,۰۰۰,۰۰۰",
    meterPrice: "۸۶,۰۰۰,۰۰۰",
  },

  {
    id: 3,
    images: ["3.webp", "8.webp", "9.webp"],
    title: "خانه باغ زیبا",
    type: "خانه باغ",
    deal: "فروش",
    area: "۳۰۰ متر",
    rooms: "۴ خواب",
    parking: "پارکینگ",
    location: "کردان",
    totalPrice: "۲۰,۰۰۰,۰۰۰,۰۰۰",
    meterPrice: "۶۵,۰۰۰,۰۰۰",
  },

  {
    id: 4,
    images: ["4.webp"],
    title: "پنت هاوس مدرن",
    type: "آپارتمان",
    deal: "فروش",
    area: "۲۲۰ متر",
    rooms: "۳ خواب",
    parking: "پارکینگ",
    location: "تهران",
    totalPrice: "۲۵,۰۰۰,۰۰۰,۰۰۰",
    meterPrice: "۱۱۰,۰۰۰,۰۰۰",
  },

  {
    id: 5,
    images: ["5.webp"],
    title: "ویلای جنگلی شمال",
    type: "ویلا",
    deal: "اجاره",
    area: "۳۵۰ متر",
    rooms: "۵ خواب",
    parking: "پارکینگ",
    location: "مازندران",
    totalPrice: "۸,۰۰۰,۰۰۰,۰۰۰",
    meterPrice: "۲۵,۰۰۰,۰۰۰",
  },

  {
    id: 6,
    images: ["6.webp"],
    title: "آپارتمان نوساز",
    type: "آپارتمان",
    deal: "فروش",
    area: "۱۴۰ متر",
    rooms: "۲ خواب",
    parking: "پارکینگ",
    location: "تهران",
    totalPrice: "۹,۰۰۰,۰۰۰,۰۰۰",
    meterPrice: "۶۵,۰۰۰,۰۰۰",
  },

  {
    id: 7,
    images: ["7.webp"],
    title: "خانه ویلایی بزرگ",
    type: "ویلا",
    deal: "فروش",
    area: "۴۰۰ متر",
    rooms: "۵ خواب",
    parking: "پارکینگ",
    location: "لواسان",
    totalPrice: "۳۰,۰۰۰,۰۰۰,۰۰۰",
    meterPrice: "۷۵,۰۰۰,۰۰۰",
  },

  {
    id: 8,
    images: ["8.webp"],
    title: "ملک تجاری",
    type: "تجاری",
    deal: "خرید",
    area: "۱۲۰ متر",
    rooms: "-",
    parking: "پارکینگ",
    location: "تهران",
    totalPrice: "۱۸,۰۰۰,۰۰۰,۰۰۰",
    meterPrice: "۱۵۰,۰۰۰,۰۰۰",
  },

  {
    id: 9,
    images: ["9.webp"],
    title: "ویلای خاص و لوکس",
    type: "ویلا",
    deal: "فروش",
    area: "۵۰۰ متر",
    rooms: "۶ خواب",
    parking: "پارکینگ",
    location: "لواسان",
    totalPrice: "۵۰,۰۰۰,۰۰۰,۰۰۰",
    meterPrice: "۱۰۰,۰۰۰,۰۰۰",
  },
];
